package com.tdin360.zjw.marathon;

/**
 * Created by jeffery on 2017/9/16.
 * 枚举类
 */

public enum EnumEventBus {
    SIGN,PHONE,CIRCLECOMMENT,ORDER,ORDERHOTELCANCEL,CIRCLEDETAILCOMMENT,WEBVIEW,BIND,CIRCLE,NOTICE,CIRCLENOTICE,EXIT,PUBLISH
}
